ITLab29/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ITLab29.Exceptions;
using ITLab29.Models.Domain;
using Microsoft.AspNetCore.Mvc;

namespace ITLab29.Controllers
{
    public class AnnouncementController : Controller
    {
        private readonly IAnnouncementRepository _announcementRepository;

        public AnnouncementController(IAnnouncementRepository announcementRepository) {
            _announcementRepository = announcementRepository;
        }

        public IActionResult Index()
        {
            List<Announcement> announcements;
            try
            {
                announcements = _announcementRepository.GetAll().OrderByDescending(a => a.PostTime).ToList();
            }
            catch (EmptyListException e)
            {
                Console.Error.WriteLine(e.StackTrace);
                announcements = new List<Announcement>();
            }
            return View(announcements);
        }
    }
}

ITLab29/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ITLab29.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ITLab29/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITLab29</title>
    <link rel="stylesheet" href="~/css/full-width-pics.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel="stylesheet" href="~/lib/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/css/mdb.min.css">
    <link rel="stylesheet" href="~/lib/css/style.css">

</head>
@{ 
    bool isAuth = User.Identity.IsAuthenticated;
}
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Session" asp-action="Index">ITLab</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Announcement" asp-action="Index">Aankondigingen</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact</a>
                    </li>
                    @{ if (isAuth) {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Session" asp-action="OpenSessions">Sessies</a>
                            </li>
                        }}
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>




    <div class="container mb-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-8">
        <div class="container">
            &copy; 2020 - ITLab
            <a href="https://www.hogent.be">
                <img src="~/photo/hogent_logo.png" style="height: 1.5em; margin-left: 1em;" />
            </a>
                <a href="https://www.facebook.com/groups/HoGentITLab/"><img src="~/photo/1200px-Facebook_icon.png" style="height: 1.5em; margin-left: 1em;" /></a>
        </div>
    </footer>
    <script type="text/javascript" src="~/lib/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/js/popper.min.js"></script>
    <script type="text/javascript" src="~/lib/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/lib/js/mdb.min.js"></script>
    <script src="~/lib/js/addons/rating.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script>
        $('#stars').mdbRate();
        $(document).ready(function(){
          $("#tableSearch").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
              $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
          });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>